version: '3'

services:
  db-med-voll:
    container_name: db-med-voll
    image: mysql:8.0.32
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - net_med_voll
    environment:
      MYSQL_DATABASE: med_voll
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'
      - 'db-data:/etc/mysql/conf.d/my.cnf'
      - 'db-data:/docker-entrypoint-initdb.d'
#  flyway:
#    container_name: flyway
#    image: flyway/flyway:6.4.1-alpine
#    networks:
#      - net_med_voll
#    environment:
#      FLYWAY_EDITION: community
#    #command: -url=jdbc:mysql://db-med-voll:3306/med_voll -schemas=med_voll -user=root -password=root -connectRetries=60 migrate
#    command: migrate
#    volumes:
#      - ./src/main/resources/db/migration:/flyway/sql/
#      - ./flyway.conf:/flyway/conf/flyway.conf
volumes:
  db-data: ~

networks:
  net_med_voll:
    external: true