spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/med_voll
    username: root
    password: root
#Mudar o nome dos parametros do Pageable na query
#  data:
#    web:
#      pageable:
#        page-parameter: pagina
#        size-parameter: tamanho
#        sort-parameter: ordem
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: 12345678